services:
  # - type: web
  #   name: 'hikma-health-admin'
  #   runtime: node
  #   buildCommand: npm run build
  #   startCommand: npm run start
  #   envVars:
  #     - key: HIKMA_API
  #       value: "VALUE_HERE"

  - type: web
    name: "hikma-health-server"
    runtime: node
    # Uncomment if you want to deploy to the free tier first.
    # NOTE: free tier has degraded performance making it unusable in real world settings
    # plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start

    envVars:
      # DATABASE_URL trumps all other env variables.
      - key: DATABASE_URL
        fromDatabase:
          name: hikma-health-db
          property: connectionString
      - key: NODE_VERSION
        value: "22.14.0"

databases:
  - name: "hikma-health-db"
    # Uncomment this line to use the free tier of the database
    # NOTE: FREE DATABASES ARE DELETED AFTER 90 DAYS!!! Remember NEVER to use a free database after for real patient data.
    # plan: free
    databaseName: hhdb
    user: hikma
    # highAvailability:
    # enabled: true
# Define any additional services or database configurations if needed
